
export const STRINGS = {
    en: {
        appName: "WorkHaat",
        tagline: "Hire smart. Earn fast.",
        heroTitle: "Find talent. Deliver results.",
        heroSubtitle: "Post a job in minutes, receive vetted proposals, pay securely when work is delivered.",
        postJob: "Post a Job",
        createGig: "Create a Gig",
        login: "Login",
        logout: "Logout",
        dashboard: "Dashboard",
        howItWorks: "How it works",
        forClients: "For Clients",
        forFreelancers: "For Freelancers",
        clientStep1: "Post Your Job",
        clientStep1Desc: "Describe your project and the skills you need.",
        clientStep2: "Hire Freelancers",
        clientStep2Desc: "Browse proposals and hire your perfect match.",
        clientStep3: "Pay Securely",
        clientStep3Desc: "Pay through our secure escrow system upon work approval.",
        freelancerStep1: "Create Your Profile",
        freelancerStep1Desc: "Showcase your skills and create attractive gigs.",
        freelancerStep2: "Find Work",
        freelancerStep2Desc: "Apply for jobs that match your expertise.",
        freelancerStep3: "Get Paid",
        freelancerStep3Desc: "Receive your earnings quickly and securely.",
        featuredCategories: "Featured Categories",
        topTalent: "Discover Top Talent",
        trustSignalsTitle: "Your peace of mind is our priority",
        paymentSecured: "Secure Payments",
        verifiedProfiles: "Verified Profiles",
        disputeSupport: "Dispute Support",
        ctaTitle: "Start free. Pay only when you hire.",
        getStarted: "Get Started",
        myJobs: "My Jobs",
        proposals: "Proposals",
        contracts: "Contracts",
        myGigs: "My Gigs",
        proposalsSent: "Proposals Sent",
    },
    hi: {
        appName: "वर्कहाट",
        tagline: "स्मार्ट हायर करें। तेजी से कमाएं।",
        heroTitle: "प्रतिभा खोजें। परिणाम दें।",
        heroSubtitle: "मिनटों में जॉब पोस्ट करें, जाँचे हुए प्रस्ताव प्राप्त करें, काम पूरा होने पर सुरक्षित रूप से भुगतान करें।",
        postJob: "जॉब पोस्ट करें",
        createGig: "गिग बनाएं",
        login: "लॉग इन करें",
        logout: "लॉग आउट",
        dashboard: "डैशबोर्ड",
        howItWorks: "यह कैसे काम करता है",
        forClients: "क्लाइंट के लिए",
        forFreelancers: "फ्रीलांसर के लिए",
        clientStep1: "अपनी जॉब पोस्ट करें",
        clientStep1Desc: "अपने प्रोजेक्ट और आवश्यक कौशल का वर्णन करें।",
        clientStep2: "फ्रीलांसर हायर करें",
        clientStep2Desc: "प्रस्ताव ब्राउज़ करें और अपना सही मैच चुनें।",
        clientStep3: "सुरक्षित भुगतान करें",
        clientStep3Desc: "काम की मंजूरी पर हमारे सुरक्षित एस्क्रो सिस्टम के माध्यम से भुगतान करें।",
        freelancerStep1: "अपनी प्रोफाइल बनाएं",
        freelancerStep1Desc: "अपने कौशल का प्रदर्शन करें और आकर्षक गिग बनाएं।",
        freelancerStep2: "काम खोजें",
        freelancerStep2Desc: "अपनी विशेषज्ञता से मेल खाने वाली नौकरियों के लिए आवेदन करें।",
        freelancerStep3: "भुगतान प्राप्त करें",
        freelancerStep3Desc: "अपनी कमाई जल्दी और सुरक्षित रूप से प्राप्त करें।",
        featuredCategories: "विशेष श्रेणियाँ",
        topTalent: "शीर्ष प्रतिभा खोजें",
        trustSignalsTitle: "आपकी मन की शांति हमारी प्राथमिकता है",
        paymentSecured: "सुरक्षित भुगतान",
        verifiedProfiles: "सत्यापित प्रोफाइल",
        disputeSupport: "विवाद सहायता",
        ctaTitle: "मुफ़्त में शुरू करें। केवल तभी भुगतान करें जब आप हायर करें।",
        getStarted: "शुरू हो जाओ",
        myJobs: "मेरी नौकरियां",
        proposals: "प्रस्ताव",
        contracts: "अनुबंध",
        myGigs: "मेरे गिग्स",
        proposalsSent: "भेजे गए प्रस्ताव",
    }
};

export const CATEGORIES = [
    "Design",
    "Development",
    "Content",
    "Marketing",
    "Video",
    "Data"
];
